# -*- coding: utf-8 -*-
"""A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ozvF21O2_odi42qyn9jaX1t23SKW0aS8
"""

temperatura_fh = float(input("Digite a temperatura em FH: "))
temperatura_celsius = (temperatura_fh - 32) * 5/9
print(" A temperatura em celsius é: {temperatura_celsius}C")



n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
M = (n1+n2)/2
if M>=7:
  print("Aprovado")
elif 4<= M <7:
  print("Você irá para a AF")
else:
  print("Reprovado")

af = float(input("Digite a nota da AF: "))
nota_af = (af + M)/2
if nota_af >5:
  print("Aprovado")
else:
  print("Reprovado")

n1 = float(input('digite um número: '))
n2 = float(input('digite um número: '))
R = n1 * n2
print(f'O resultado da multiplicação é: {R} ')

notas = []
for i in range(2):
  nota =   float(input(f'Digite a {i+1} nota: '))
  notas.append(nota)
media = sum(notas)/len(notas)
print(f'A média é: {media}')

peso = float(input('Digite seu peso: '))
altura = float(input('Digite sua altura: '))
IMC = peso/(altura*altura)
print((f'Seu IMC é: {IMC}'))

notas = []
for i in range(3):
    nota =  float(input(f'Digite a {i+1} nota: '))
    notas.append(nota)
    media = sum(notas)/3
print(f'A média aritimética é: {media} ')

#Faça um programa que receba um número n inteiro digitado pelo usuário (assuma que
#ele sempre vai digitar um inteiro). Mostre:
#a) quadrado de n
#b) dobro de n
#c) triplo de n
#d) resto da divisão de n por 2
#e) resultado da divisão de n por 3

n = int(input('Digite um número: '))

dobro_n = n * 2
qua_n = n * n
tri_n = n * n * n
resto_n2 = n % 2
divisao3_n = n / 3

print(f'O dobro de {n} é: {dobro_n}')
print(f'O quadrado de {n} é: {qua_n}')
print(f'O triplo  de {n} é: {tri_n}')
print(f'O resto da divisão de {n} é: {resto_n2}')
print(f'A divisão por três de {n} é: {divisao3_n}')

# Faça um programa que receba 3 números inteiros (assuma que sempre serão digitados
#números inteiros). Informe caso os três sejam iguais, se são todos diferentes ou se dois dos três são
#iguais



n1 = int(input("Digite o primeiro número: "))
n2 = int(input("Digite o segundo número: "))
n3 = int(input("Digite o terceiro número: "))

if n1 == n2 and n1 == n3:
    print('Todos são iguais!')
elif n1 == n2 or n1 == n3 or n2 == n3:
    print("Dois são iguais!")
else:
    print('Todos são diferentes!')

#Faça um programa que pede, continuamente, para o usuário digitar números inteiros
#(assuma que sempre serão digitados números inteiros). O programa deve parar de solicitar números
#quando o usuário digitar o número 0. Ao fim, mostre a soma de todos os números digitados e o total
#de números digitados.


total_numeros = 0
soma = 0
while True:
  n = int(input('Digite quantos números desejar: '))
  if n == 0:
   break
  soma+= n
  total_numeros+=1

print(f"A soma dos números digitados foi: {soma}")
print(f"O total de números digitados foi: {total_numeros}")

# Escreva um programa que pede um número n entre 1 e 9 (assuma que sempre será
#digitado um número inteiro e encerre o programa caso o número digitado não esteja nesta faixa).
#Imprima a soma da sequência de n números formados por n’s consecutivos. Exemplo: n=3;
#Sequência com 3 (n) números formados 3’s (n’s) consecutivos: 3, 33, 333. Soma da sequência: 369

n = int(input('Digite um número de 1 a 9: '))
if 1< n <=9:
  soma = 0
  sequencia_numeros = 0

  for i in range(1, n+1):
    sequencia_numeros = sequencia_numeros* 10 + n
    soma += sequencia_numeros

  print(f'A sequência do número é: {sequencia_numeros}')
  print(f'A soma dos números é: {soma}')

#Faça um programa que recebe um número n e uma operação matemática (soma ‘+’ ou
#multiplicação ‘*’) e mostre a tabuada da operação selecionada do número n de 1 até 10. Encerre o
#programa com uma mensagem de “Operação inválida!” caso o usuário não digite ‘+’ ou ‘*’. Encerre
#também o programa com uma mensagem de “Número inválido!” caso a pessoa digite um número
#negativo

# Solicita um número e uma operação matemática
n = int(input("Digite um número: "))
operacao = input("Digite a operação desejada (+ para soma, * para multiplicação): ")

# Verifica se o número é negativo
if n < 0:
    print("Número inválido! Encerrando o programa.")
else:
    # Verifica a operação selecionada
    if operacao == '+' or operacao == '*':
        # Imprime a tabuada da operação selecionada
        print(f"Tabuada de {n} para a operação {operacao}:")
        for i in range(1, 11):
            if operacao == '+':
                resultado = n + i
            else:
                resultado = n * i
            print(f"{n} {operacao} {i} = {resultado}")
    else:
        # Caso a operação seja inválida
        print("Operação inválida! Encerrando o programa.")